version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_opendata
    restart: always
    environment:
      POSTGRES_DB: opendata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@exemplo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"  # pgAdmin em localhost:8080
    depends_on:
      - postgres
    networks:
      - pg_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  pg_network:
    driver: bridge
